<?php
    $apiKey = "rzp_test_3N4mlXquypGLFx";
    $amt=$_POST['amount']*100;
?>
<script src="https://code.jquery.com/jquery-3.5.0.js"></script>
<form action="success.php" method="POST">
<script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="<?php echo $apiKey; ?>" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    data-amount="<?php echo $amt; ?>" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR"// You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-id="<?php echo 'OID'.rand(10,100).'END';?>"// Replace with the order_id generated by you in the backend.
    data-buttontext="Pay with Razorpay"
    data-name="GREEN HOSTEL"
    data-description="A BEAUTIFUL PLACE TO STAY"
    data-image="https://scontent.fhyd14-2.fna.fbcdn.net/v/t39.30808-6/277803994_392907116173465_522846828618564559_n.png?_nc_cat=100&ccb=1-7&_nc_sid=5f2048&_nc_ohc=aOTo1bW85bcAX9GpC7O&_nc_ht=scontent.fhyd14-2.fna&oh=00_AfAq7N0hHYSCvO3R527A5kaovMJqxZnhobD5eG3oQSXW9w&oe=65FB3230"
    data-prefill.firstname="<?php echo $_POST['firstname'];?>"
    data-prefill.phone number="<?php echo $_POST['phoneno'];?>"
    data-theme.color="#F37254"
></script>
<input type="hidden" custom="Hidden Element" name="hidden"/>
</form> 
<style>.razorpay-payment-button{display:none;}
</style>
<script type="text/javascript">
$(document).ready(function(){
$('.razorpay-payment-button').click();
}); 
</script>